### Filter
get http://localhost:3003/api/tickets?status=todo

### getOne
get http://localhost:3003/api/tickets/01JYF1PE3Y8NHDXVVG66V1T3PF

### udpate
PUT  http://localhost:3003/api/tickets/01JYF1JZAJRPGXJPSEG34TAW7Z/move
Content-Type: "application/json"

{
    "status": "inProgress"
}

### delete
DELETE http://localhost:3003/api/tickets/01JYF12RS4V9WDTB8AHQT8Y7ZF

### Create

post http://localhost:3003/api/tickets
Content-Type: "application/json"

{
    "title": "Another Stuff",
    "body": "Bloppo Blippo [cacca](pupu.com)"
}