### Filter
get http://localhost:3003/api/tickets?statuses=todo,inProgress,backlog

### getOne
get http://localhost:3003/api/tickets/01JZ5WE7A0RQTNFY0B188D8HVG

### link
POST  http://localhost:3003/api/tickets/01JZ8CRNQ7S69AHR9X541A97ZR/link
Content-Type: "application/json"

{
    "type": "linked",
    "linkedId": "01JZ8E15XQ8CZ71KXKJT6TXDG6"
}

### unlink
DELETE  http://localhost:3003/api/tickets/01JZ5WE7A1ZKRXG2WW1DWFPJPQ/link/01JZ5WE7A0RQTNFY0B188D8HVG

### udpate
PUT  http://localhost:3003/api/tickets/01JYRK01WZ69BYMSTDHMM5QR80
Content-Type: "application/json"

{
    "type": "bug",
    "status": "inProgress"
}

### move
PUT  http://localhost:3003/api/tickets/01JYTHB24E0H7D29THF7ZX6NFY/move
Content-Type: "application/json"

{
    "status": "flappo"
}

### archive
POST  http://localhost:3003/api/tickets/01JZ3282YH09KWEBWVF5X82REF/archive


### delete
DELETE http://localhost:3003/api/tickets/01JZ837XDVDS9QSMQT7Y9HBTH0

### Create

post http://localhost:3003/api/tickets
Content-Type: "application/json"

{
    "title": "Make some stuff with the thing",
    "body": "Bloppo Blippo",
    "status": "todo"
}