### Filter
get http://localhost:3003/api/tickets?statuses=todo,inProgress

### getOne
get http://localhost:3003/api/tickets/01JYF1PE3Y8NHDXVVG66V1T3PF

### udpate
PUT  http://localhost:3003/api/tickets/01JYF5F18Z9CYGKG7B080JK95Y/move
Content-Type: "application/json"

{
    "status": "todo"
}

### delete
DELETE http://localhost:3003/api/tickets/01JYF12RS4V9WDTB8AHQT8Y7ZF

### Create

post http://localhost:3003/api/tickets
Content-Type: "application/json"

{
    "title": "Another Stuff",
    "body": "Bloppo Blippo [cacca](pupu.com)"
}