### Filter
get http://localhost:3003/api/tickets?statuses=todo,inProgress,backlog

### getOne
get http://localhost:3003/api/tickets/01JYF1PE3Y8NHDXVVG66V1T3PF

### udpate
PUT  http://localhost:3003/api/tickets/01JYRK01WZ69BYMSTDHMM5QR80
Content-Type: "application/json"

{
    "type": "bug",
    "status": "inProgress"
}

### move
PUT  http://localhost:3003/api/tickets/01JYTHB24E0H7D29THF7ZX6NFY/move
Content-Type: "application/json"

{
    "status": "flappo"
}

### archive
POST  http://localhost:3003/api/tickets/01JZ3282YH09KWEBWVF5X82REF/archive


### delete
DELETE http://localhost:3003/api/tickets/01JYF12RS4V9WDTB8AHQT8Y7ZF

### Create

post http://localhost:3003/api/tickets
Content-Type: "application/json"

{
    "title": "Thingy333",
    "body": "Bloppo Blippo",
    "status": "inProgress",
    "tags":["mario", "cacca"]
}